version: '3.8'
services:
  dspy-app:
    build: .
    container_name: dspy-app
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - .:/app
    working_dir: /app
    command: ["python3", "src/main.py", "--task", "benchmark"]
